version: 2.1
orbs:
  python: circleci/python@1.2

workflows:
  build-app-with-test:
    jobs:
      - lint-code
      - build-and-test:
          requires:
            - lint-code
jobs:
  lint-code:
      working_directory: ~/blogAPI
      docker:
          - image: cimg/node:16.13.2
      steps:
          - checkout
          - run:
                name: update npm
                command: 'sudo npm install -g npm'
          - run:
                name: install dependencies
                command: sudo npm install
          - run:
                name: run test
                command: npm test

  build-and-test:
      working_directory: ~/blogAPI
      docker:
          - image: cimg/node:16.13.2
      steps:
          - checkout
          - run:
                name: lint code
                command: npm run lint:check
