version: 2.1


workflows:
    lint-build-test:
        when:
          or: # you can also specify multiple conditions here
            - equal: [ main, << pipeline.git.branch >> ]
            - equal: [ staging, << pipeline.git.branch >> ]
        jobs:
            - lint-code
            - hold: # <<< A job that will require manual approval in the CircleCI web application.
                type: approval # <<< This key-value pair will set your workflow to a status of "On Hold"
                requires: # We only run the "hold" job when lint-code has succeeded
                 - lint-code
            # On approval of the `hold` job, any successive job that requires the `hold` job will run.
            # In this case, a user is manually triggering the deploy job.
            - build-and-test:
                  requires:
                      - hold
        
jobs:
    lint-code:
        docker:
            - image: cimg/node:16.13.2
        steps:
            - checkout
            - run:
                  name: update npm
                  command: 'sudo npm install -g npm'

            - run:
                  name: install dependencies
                  command: sudo npm install

            - run:
                  name: lint code
                  command: npm run lint:check

    build-and-test:
        docker:
            - image: cimg/node:16.13.2
        steps:
            - checkout
            - run:
                  name: update npm
                  command: 'sudo npm install -g npm'

            - run:
                  name: install dependencies
                  command: sudo npm install

            - run:
                  name: run tests
                  command: npm test

